[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "hubspot.crm.engagement.notes"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["engagement", "notes", "Vendor/HubSpot", "Area/CRM", "Type/Connector"]
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.engagement.notes"

[build-options]
observabilityIncluded = true
